name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build-and-test:
    runs-on: docker
    steps:
      - name: Checkout
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          git init -q
          git remote add origin https://andeerc:${FORGEJO_TOKEN}@codeberg.org/andeerc/sparrow.git
          git fetch origin --depth 1 ${GITHUB_REF_NAME}
          git checkout FETCH_HEAD

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Lint (clippy)
        run: cargo clippy -- -D warnings

      - name: Format check
        run: cargo fmt --check

      - name: Security audit
        run: |
          cargo install cargo-audit --locked
          cargo audit

      - name: Build
        run: cargo build --release --locked

      - name: Test
        run: cargo test --workspace
